version: '3'
services:
  dind:
    # Starts a Docker daemon at the DNS name "docker"
    # Note:
    #  * This must be called "docker" to line up with the default
    #    TLS certificate name
    #  * DOCKER_TLS_CERTDIR defaults to "/certs
    image: docker:dind
    container_name: dind
    ports:
      - 2376:2376
    privileged: yes
    volumes:
      - ./certs/ca:/certs/ca
      - ./certs/client:/certs/client
      - ./data:/var/lib/docker